### ISSUE TITLE
Can you support Roon Extensions?

### ISSUE THREAD

**Issue by JoeCotellese** [steefdebruijn/docker-roonserver#11]
Hey, I love using this on my Unraid server but I can't figure out how to install extensions. Is that something you can add? Maybe default to installing the Roon Extension manager?

**Comment by steefdebruijn** [comment]
Hi,

The extension manager has its own docker image, provided by another Roon enthousiast:

https://hub.docker.com/r/theappgineer/roon-extension-manager

I have no intentions to add this to the server image. A docker container should do one thing and adding the extension manager to the server image would break this 'rule' and complicate the image maintainance for me.

So, if you would like to use extensions, run the above extension manager next to your server container and i guess they will find each other by discovery.

If you try this please report back, I can add a section to the docs to explain this procedure.

(i am in the process of recovering from a total server failure so cannot try this myself for the coming weeks)

Steef

**Comment by xthursdayx** [comment]
I've actually also been working on coordinating these two since I maintain the unRAID Roon template. I should be updating the Roon thread in the unRaid forums soon about this, but feel free to be in touch with me here or on the unRAID forums @JoeCotellese to follow up if you don't hear anything from me soon. 

(Also @steefdebruijn as an aside I feel your pain re: the server loss - I just recently had the cache drive in my server die, taking with it my `docker.img`, all the docker volumes that weren't host mounted to my main array, several VM virtual discs, and all of my `appdata` config and database directories. Luckily most of these (other than the internal docker volumes) were backed up, but it's still major pain to get everything set up again. I don't envy your struggle, but best wishes as you deal withe recovery process!)
